#include <algorithm>
#include <array>
#include <cassert>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <vector>

#ifdef NDEBUG
#error "verification requires assertions; compile without -DNDEBUG"
#endif

using Map = std::array<int, 6>;
using Edge = std::array<int, 2>;

const Map A{0, 1, 0, 0, 1, 0};
const Map C{3, 4, 5, 1, 2, 1};
const Map ID{0, 1, 2, 3, 4, 5};
const std::array<Map, 2> generators{A, C};
const std::set<Edge> edges{{0, 1}, {1, 2}, {3, 4}, {4, 5}};

Map compose(const Map& left, const Map& right) {
  Map out{};
  for (int i = 0; i < 6; ++i) out[i] = left[right[i]];
  return out;
}

int rank(const Map& f) {
  return std::set<int>(f.begin(), f.end()).size();
}

std::vector<std::vector<int>> kernel(const Map& f) {
  std::map<int, std::vector<int>> by_image;
  for (int i = 0; i < 6; ++i) by_image[f[i]].push_back(i);
  std::vector<std::vector<int>> out;
  for (auto& item : by_image) out.push_back(item.second);
  std::sort(out.begin(), out.end());
  return out;
}

std::vector<int> profile(const Map& f) {
  std::vector<int> out;
  for (const auto& block : kernel(f)) out.push_back(block.size());
  std::sort(out.begin(), out.end());
  return out;
}

bool is_edge(int x, int y) {
  if (x > y) std::swap(x, y);
  return edges.count({x, y});
}

bool is_endomorphism(const Map& f) {
  for (auto edge : edges) if (!is_edge(f[edge[0]], f[edge[1]])) return false;
  return true;
}

int main() {
  assert(is_endomorphism(A) && is_endomorphism(C));

  // Independent reachability check for the transition matrix whose two
  // positive entries in each row are generated by fair A/C choices.
  for (int source = 0; source < 6; ++source) {
    std::set<int> seen{source};
    std::queue<int> todo;
    todo.push(source);
    while (!todo.empty()) {
      int u = todo.front(); todo.pop();
      for (const Map& f : generators) {
        if (seen.insert(f[u]).second) todo.push(f[u]);
      }
    }
    assert(seen.size() == 6);
  }

  // Build the actual prefix-state Markov chain M_t=F_t o M_{t-1}, starting
  // at the identity, rather than closing an abstract multiplication table.
  std::set<Map> states{ID};
  std::queue<Map> todo;
  todo.push(ID);
  while (!todo.empty()) {
    Map current = todo.front(); todo.pop();
    for (const Map& next_function : generators) {
      Map next = compose(next_function, current);
      if (states.insert(next).second) todo.push(next);
    }
  }
  assert(states.size() == 22); // identity plus the 21-element semigroup
  int minimum_rank = 6;
  for (const Map& state : states) {
    assert(state == ID || is_endomorphism(state));
    minimum_rank = std::min(minimum_rank, rank(state));
    if (rank(state) == 2) {
      for (const Map& next_function : generators) {
        Map next = compose(next_function, state);
        assert(rank(next) == 2);
        assert(kernel(next) == kernel(state));
      }
    }
  }
  assert(minimum_rank == 2);

  const Map balanced = compose(A, C);
  assert(profile(A) == std::vector<int>({2, 4}));
  assert(profile(balanced) == std::vector<int>({3, 3}));

  // First supported word A has probability 1/2; first word C,A has
  // probability 1/4. Their kernels are terminal under every continuation.
  std::cout << "independent prefix-chain verification: PASS\n";
  std::cout << "reachable_states=22 min_rank=2 profiles=(2,4),(3,3)\n";
  std::cout << "positive_prefix_probabilities=1/2,1/4\n";
}
